
set(CMAKE_SYSTEM_NAME Linux)
set(CMAKE_SYSTEM_PROCESSOR aarch64)
set(TRIPLET aarch64-none-linux-gnu)
set(TRIPLET_TOOL aarch64-linux-gnu)

set(ENV{COMPILER_PATH} "/chroots/aarch64-none-linux-gnu/bin")

set(SYSROOT_PATH "/chroots/${TRIPLET}")
set(CMAKE_SYSROOT "${SYSROOT_PATH}")
set(CMAKE_FIND_ROOT_PATH "${SYSROOT_PATH}")

set(CMAKE_CROSSCOMPILING_EMULATOR "/usr/bin/qemu-aarch64-static;-L;/usr/aarch64-linux-gnu")

set(TOOL_PREFIX "/chroots/bin/${TRIPLET}")
set(CMAKE_LIBRARY_ARCHITECTURE "${TRIPLET_TOOL}")
set(CMAKE_C_COMPILER "${SYSROOT_PATH}/bin/${TRIPLET_TOOL}-gcc")
set(CMAKE_CXX_COMPILER "${SYSROOT_PATH}/bin/${TRIPLET_TOOL}-g++")
set(CMAKE_ASM_COMPILER "${SYSROOT_PATH}/bin/${TRIPLET_TOOL}-gcc")

set(CMAKE_TRY_COMPILE_TARGET_TYPE STATIC_LIBRARY)

set(CMAKE_AR "${SYSROOT_PATH}/bin/${TRIPLET_TOOL}-ar" CACHE FILEPATH "Archiver")
set(CMAKE_RANLIB "${SYSROOT_PATH}/bin/${TRIPLET_TOOL}-ranlib" CACHE FILEPATH "Ranlib")
set(CMAKE_READELF "${SYSROOT_PATH}/bin/${TRIPLET_TOOL}-readelf" CACHE FILEPATH "Readelf")
set(CMAKE_AS "${SYSROOT_PATH}/bin/${TRIPLET_TOOL}-as" CACHE FILEPATH "Assembler")
set(CMAKE_LINKER "${SYSROOT_PATH}/bin/${TRIPLET_TOOL}-ld" CACHE FILEPATH "Linker")

set(CMAKE_EXE_LINKER_FLAGS "-Wl,-rpath-link,${SYSROOT_PATH}/usr/lib/aarch64-linux-gnu:${SYSROOT_PATH}/lib/aarch64-linux-gnu -L${SYSROOT_PATH}/usr/lib/aarch64-linux-gnu -L${SYSROOT_PATH}/lib/aarch64-linux-gnu" CACHE STRING "" FORCE)
set(CMAKE_SHARED_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "" FORCE)
set(CMAKE_MODULE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS}" CACHE STRING "" FORCE)
list(APPEND CMAKE_PREFIX_PATH "${SYSROOT_PATH}")

set(CMAKE_CXX_STANDARD 17)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -D_GNU_SOURCE")
set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -D_GNU_SOURCE")

set(CMAKE_FIND_ROOT_PATH "${SYSROOT_PATH}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

set(PIP_CMG ${SYSROOT_PATH}/usr/local/bin/pip_cmg)
set(PIP_RC ${SYSROOT_PATH}/usr/local/bin/pip_rc)
set(PIP_TR ${SYSROOT_PATH}/usr/local/bin/pip_tr)
set(PIP_DEPLOY_TOOL ${SYSROOT_PATH}/usr/local/bin/pip_deploy_tool)
set(PIP_H_INCLUDE ${SYSROOT_PATH}/usr/local/include/pip/pip_version.h)
set(Boost_DIR ${SYSROOT_PATH}/usr/lib/${TRIPLET_TOOL}/cmake/Boost-1.83.0)

set(CMAKE_INSTALL_PREFIX "${CMAKE_CURRENT_SOURCE_DIR}/bin" CACHE PATH "Install path" FORCE)

#include_directories("${CMAKE_PREFIX_PATH}/include" "${CMAKE_PREFIX_PATH}/include/${TRIPLET}")
cmake_policy(SET CMP0025 NEW)